// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Test(Props) {
  return React.createElement("div", {
              className: "text-red-400"
            }, "Hello World");
}

var make = Test;

export {
  make ,
  
}
/* react Not a pure module */
